### PR TITLE
Updated the old snippets a bit and added some new

### PR DESCRIPTION
**Pull request by gausby**
The following has been added:
- a template for behaviours: `Behaviour`
- protocols: `defprotocol`, and `defimpl`
- Generic module structures: `Application`, `GenEvent`, and `GenServer`
- Blocks: `receive`, and `do`
- Unnamed functions: `fn`
- List comprehensions: `for`
- Simple logic blocks: `if`, and `unless`
- A `test` snippet that expand to a basic ExTest

Snippets are all about personal taste. I've tried to keep them very generic. See if you like it.

### CODE REVIEW

**Comment by edubkendo** [comment]
awesome work, temporarily using your fork. hope this gets merged! one suggestion, I made a tiny change and removed the extra newline in the `def` and `defp` snippets so I don't wind up with that extra line between the last two `end`s in a module.  Like:

```elixir
defmodule App do
  def func(arg) do
    #
  end

end
```

Which continually aggravates me. Just two-cents from a user. Thanks again, this is really handy.

**Comment by gausby** [comment]
@edubkendo thanks, and great suggestion. I'll update my PR as soon as possible!

**Comment by gausby** [comment]
...scratch that, I've updated the `def` and `defp` snippets ;)

**Comment by hisea** [comment]
Thank you for your contribution @gausby and @edubkendo

**Pull request merged**
